### ISSUE TITLE
KGEN does not generate valid fortran code

### ISSUE THREAD

**Issue by johnmauff** [NCAR-CISL-ASAP/KGen#119]
When a comment line follows a declaration statement KGEN generates invalid fortran.  An example is seen below:

        INTEGER, parameter :: dp = selected_real_kind(p=12)
    dp = selected_real_kind( p=12 )    ! double precision

This bug can be reproduced by executing make in the following directory:  /glade/p/work/dennis/generate-kernels/compute_length/kernel

**Comment by amsi7193** [comment]
I believe this issue has been addressed in branch issue-114.
Can you please checkout that branch and let me know if this problem still persists?
Issue-114 is up to date with all commits to devel.

**Comment by amsi7193** [comment]
John, the invalid fortran code problem has been addressed in branch
issue-114.
I have not merged it into devel because I don't think it's not a long term
solution for the source generation issues that KGen faces. Can you please
check out issue-114 and let me know if the problem persists.

Thanks,
Amogh

**Comment by johnmauff** [comment]
Amogh,

  Well it eliminated the invalid fortran code.  However, now the kernel is
missing a symbol:

advance_clubb_core_module.o: In function
`advance_clubb_core_module_mp_advance_clubb_core_':
advance_clubb_core_module.F90:(.text+0x173): undefined reference to
`kgen_verify_integer_'

**Comment by amsi7193** [comment]
This is strange. I was able to extract my test kernels with this. I will
look into it right away and get back to you asap.

-Amogh

**Comment by amsi7193** [comment]
The missing symbol is a result of an intrinsic type integer being passed as an argument to the kernel. err_code is an inout integer that needs to be verified. However, KGen does not correctly generate the verification subroutine.
The progress up to this point has been summarized below - 
All updates are in branch issue-119
In **kgen_genkernel.py**, in function *generate_kernel_module_callsite()*, the calling module is generated. At line 692, a call to *write_kernel_subroutines_verify_var()* is made for all the output variables that need to be checked. There is an active breakpoint a few lines before this.
In **kgen_genutils.py**, at line 1157, in function *write_kernel_subroutines_verify_var()*, the list *tkdpatlist* is empty, therefore, no verification is done.
The object *State.parentblock['output']['tkdpat']* is empty because the intrinsic integer is not added to the list at all. This can be verified by looking at line 15 in **kgen_geninfo.py**.
The solution to this is to 1) Add support in **kgen_geninfo.py** for appending an intrinsic type to the *State.parentblock['output']['tkdpat']* list. However, this is cumbersome as it would require changing the shape of certain data structures.
2) Add a clause in **kgen_genutils.py**, in the *write_kernel_subroutines_verify_var()* function to handle intrinsic functions so that even if *tkdpatlist* is empty, Kgen will check if there is an intrinsic-type output and write the correct verification subroutine.
I believe the second method is the right way to go.

**Comment by grnydawn** [comment]
This issue was moved to NCAR/KGen#3

**Comment by grnydawn** [comment]
This issue is resolved with v0.6.1
